### PR TITLE
Update to Brunch 2.0 style

### PR DESCRIPTION
**Pull request by colinbate**
This is a pretty big PR, arguably the whole plugin has been rewritten, but I wanted to see if you were interested in merging it in. If not, I'll publish it under a different name. I needed something which worked with npm 3 and newer TypeScript and then when that didn't work, I rewrote it in the new plugin style using the TypeScript API rather than the command line tool.

### CODE REVIEW

**Comment by baptistedonaux** [comment]
Oh great, I try it quickly (in 1 or 2 hours) and I come back to merge if all works for me :)

**Comment by baptistedonaux** [comment]
It's a FU**ING good job ! Only few requests before merge.

- Please set the release version at ```1.7.0```. I index ```brunch-typescript``` on ```typescript``` release.
- Please add your name in contributors (README.md) :)

I waits last commit, I merges and I publish a new release.

**Comment by colinbate** [comment]
OK, updated the version and README. Thanks for taking a look at this.

**Comment by baptistedonaux** [comment]
@colinbate Published on npm !

**Pull request merged**
