### PR TITLE
Fixed a typo (removed a ';')

### PR DESCRIPTION
**Pull request by kripod**
I've tested this fix, and the plugin works flawlessly with it. Sorry for the inconvenience I caused!

### CODE REVIEW

**Comment by baptistedonaux** [comment]
Merged

**Comment by kripod** [comment]
Thanks! You should also increment the version by one as soon as possible, as 1.6.2 didn't work at all due to my mistake.

**Comment by baptistedonaux** [comment]
1.6.3 bumped and available. Sorry, I had forgotten.

**Comment by kripod** [comment]
Great! :+1:

**Pull request merged**
