### PR TITLE
Upgrade brunch-typescript and typescript-brunch.

### PR DESCRIPTION
**Pull request by denysdovhan**
Hey, @baptistedonaux, @jpoehls, @xtity, @colinbate and @kripod! Hello from @brunch team!

We've noticed that there are two plugins for TypeScript in Brunch ecosystem:

1. [typescript-brunch](https://www.npmjs.com/package/typescript-brunch)
2. [brunch-typescript](https://www.npmjs.com/package/brunch-typescript)

The first one has a correct name (in according to plugin's styleguide), but it seems like this plugin was abandoned. The second one (this plugin) has more downloads, better API and seems like the most popular solution for TypeScript with Brunch.

We would like to update this plugin a bit (in corresponding to brunch/brunch#1666) and merge this one with `typescript-brunch`. Would be great (if you agree, of course) to move this plugin under @brunch organization, where we will take care of this plugin.

This PR introduce few changes for merging this plugin with `typescript-brunch`. Also, I've noticed #28 — gonna keep in mind those changes.

I need your confirmation. Do you agree with that? Would you like to move this plugin under @brunch org?

Hey, @joshheyse! We need you help to get NPM ownership for `typescript-brunch` package. Could you help us with that?

---

**WIP:** Do not merge this PR! I'm still working on improvement of this plugin!

### CODE REVIEW

**Comment by joshheyse** [comment]
I'd be happy transfer the typescript-brunch package over to new ownership. Please let me know who I should coordinate with. 

Keep up the good work!

**Comment by colinbate** [comment]
Ultimately the organizational decision belongs to @baptistedonaux, but I do like the idea of getting the name in line with other brunch plugins.

Also, while this plugin may be the best option for TypeScript with Brunch at the moment, it does lack proper integration with the TypeScript language server. Currently it just compiles each file in isolation. While this works, it makes normal error reporting essentially useless. I mention this because of your intention to standardize that (with line/col numbers, etc).

As it stands, the only practical way to use this plugin is with `ignoreErrors: true` set in the plugin config.

That said, the plugin works, but you typically need another mechanism to ensure your whole code base is free of compiler errors. And for incremental building, that might be all we need. However, I would like to support full language server integration when doing a full `brunch build`. I just haven't had the time unfortunately.

I'm not sure if everyone agrees, but I think that should be a priority if things move organizations.

**Comment by denysdovhan** [comment]
@joshheyse please, add @paulmillr as an owner to your package.

**Comment by denysdovhan** [comment]
@colinbate I've updated this plugin a bit. Didn't change logic. You are welcome to collaborate.

@baptistedonaux what do you think about transfer this plugin under Brunch org? If you agree, then here is a simple to-do:

- [ ] Merge this PR
- [ ] Transfer ownership of this repo to me (you don't have permissions to Brunch org, so you can't transfer this repo directly)
- [ ] Rename package to _typescript-brunch_ (I'll do it by myself)
- [ ] Deprecate _brunch-typescript_ on NPM
- [ ] Publish new version of _typescript-brunch_

Waiting for your response.

**Comment by baptistedonaux** [comment]
Initially this plugin has been created to give a TypeScript compilator up-to-date for Brunch project. I think that to help Brunch organization to grow, this plugin must be integrated in Brunch stack.

Thank @colinbate for your features and improvements.

**Comment by baptistedonaux** [comment]
@denysdovhan Can you removed your fork ? I can't transfer it to you.

**Comment by denysdovhan** [comment]
@baptistedonaux done. I've deleted my fork.

**Comment by denysdovhan** [comment]
@baptistedonaux got it. Thank you. Moving to the Brunch repo.

**Comment by denysdovhan** [comment]
@baptistedonaux done. Repo is under Brunch org.

**Comment by baptistedonaux** [comment]
@denysdovhan How can I "Deprecate brunch-typescript on NPM" ? Do I have remove repository ?

**Comment by denysdovhan** [comment]
@baptistedonaux nonono, just execute this command:

```
npm deprecate brunch-typescript "brunch-typescript is unsupported, use typescript-brunch instead"
```

But let's wait for a while. We have to publish new version of _typescript-brunch_ plugin before.

**Comment by baptistedonaux** [comment]
Perfect ! I wait your feedback.

**Comment by denysdovhan** [comment]
@baptistedonaux I've asked @paulmillr to publish new version of _typescript-brunch_. Waiting for response from him.

@joshheyse, did you give NPM ownership to @paulmillr?

**Comment by joshheyse** [comment]
I gave @paulmillr access today. Let me know if there are issues

**Comment by paulmillr** [comment]
2.2 is out

**Comment by denysdovhan** [comment]
@baptistedonaux please, deprecate old _brunch-typescript_ plugin.

**Comment by baptistedonaux** [comment]
@denysdovhan Done

**Comment by denysdovhan** [comment]
@joshheyse @colinbate @baptistedonaux thanks you all!

**Pull request merged**
