### PR TITLE
Test and deployment integration

### PR DESCRIPTION
**Pull request by baptistedonaux**
@colinbate ```brunch-typescript``` is now used by few developers. Thank you for your job and your implication.

To help futures improvements and help others developers to contribute on this plugin, I would like add test integration and deployment integration with Travis.

```npm test``` runs simply ESLint to check that code is formatted and respect our standard (for a best readable).

Next, I would like an auto-deployment with Travis CI.

Example :
- A contributor works on a feature or a fix. A PR is sent.
- Travis runs test. Tests have positive result.
- A contributor merges this PR. He check if ```package.json``` version is correctly incremented and add a Git tag wit the same value.
- Travis runs again the test, check that Git tag as same value as ```package.json``` version and deploys then on NPM.

### CODE REVIEW

**Comment by baptistedonaux** [comment]
@colinbate Can you help me to fix the last error thrown by ESLint.

**Comment by colinbate** [comment]
Hopefully that changeset should do it.

**Comment by colinbate** [comment]
You may also want to add an `.editorconfig` file with the tab and line ending preferences. This will help others maintain consistency.

**Comment by baptistedonaux** [comment]
@colinbate Good recommendation. Please, give me your opinion on this file.

**Pull request merged**
